name: PushMaster-Build-Deploy

# Run this workflow every time there's a push to master branch
on:
  push:
    branches:
      - master

jobs:
  pushmaster-build-deploy:
    # Name the Job
    name: Push
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      # Install proyect dependencies and make a build
      - name: Install and Build 🔧
        run: |
          yarn
          yarn build
      # Deploys to github pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.1
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
